rock.namespace('app');

app.constants = {
    LOCALE_EN : 'en',
    LOCALE_ES : 'es',

    RESOURCE_LOADER_WINDOW : 'RESOURCE_LOADER_WINDOW',
    MAIN_WINDOW : 'MAIN_WINDOW',
    OPTIONS_WINDOW : 'OPTIONS_WINDOW',
    TEST_GRAPHICS_ENGINE_WINDOW : 'TEST_GRAPHICS_ENGINE_WINDOW',
    TEST_EVENTS_WINDOW : 'TEST_EVENTS_WINDOW',
    TEST_COMPONENTS_WINDOW : 'TEST_COMPONENTS_WINDOW',
    TEST_TIMER_WINDOW : 'TEST_TIMER_WINDOW',
    UNIT_TEST_WINDOW : 'UNIT_TEST_WINDOW',
    TEST_AUDIO_WINDOW :'TEST_AUDIO_WINDOW',

    RES_ID_IMG_LOGO : 'RES_ID_IMG_LOGO',
    RES_ID_IMG_ESP : 'RES_ID_IMG_ESP',
    RES_ID_IMG_ENG : 'RES_ID_IMG_ENG',
    RES_ID_IMG_CHESSBOARD : 'RES_ID_IMG_CHESSBOARD',
    RES_ID_IMG_TEST_GRAPHICS_ENGINE : 'RES_ID_IMG_TEST_GRAPHICS_ENGINE',
    RES_ID_IMG_TRANSPARENCY_TEST_GRAPHICS_ENGINE : 'RES_ID_IMG_TRANSPARENCY_TEST_GRAPHICS_ENGINE',
    RES_ID_IMAGE_COMPONENT : 'RES_ID_IMAGE_COMPONENT',
    RES_ID_AUDIO_WAV : 'RES_ID_AUDIO_WAV'
};
